// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: file_processor.proto
#ifndef GRPC_file_5fprocessor_2eproto__INCLUDED
#define GRPC_file_5fprocessor_2eproto__INCLUDED

#include "file_processor.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace file_processor {

class FileProcessorService final {
 public:
  static constexpr char const* service_full_name() {
    return "file_processor.FileProcessorService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Conversao de PDF para TXT 
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::FileChunk>> ConvertToTXT(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::FileChunk>>(ConvertToTXTRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::FileChunk>> AsyncConvertToTXT(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::FileChunk>>(AsyncConvertToTXTRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::FileChunk>> PrepareAsyncConvertToTXT(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::FileChunk>>(PrepareAsyncConvertToTXTRaw(context, cq));
    }
    // Conversao de formato de imagem
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::FileChunk>> ConvertImageFormat(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::FileChunk>>(ConvertImageFormatRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::FileChunk>> AsyncConvertImageFormat(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::FileChunk>>(AsyncConvertImageFormatRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::FileChunk>> PrepareAsyncConvertImageFormat(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::FileChunk>>(PrepareAsyncConvertImageFormatRaw(context, cq));
    }
    // Redimensionamento de imagem 
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::FileChunk>> ResizeImage(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::FileChunk>>(ResizeImageRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::FileChunk>> AsyncResizeImage(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::FileChunk>>(AsyncResizeImageRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::FileChunk>> PrepareAsyncResizeImage(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::FileChunk>>(PrepareAsyncResizeImageRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Conversao de PDF para TXT 
      virtual void ConvertToTXT(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::file_processor::FileChunk,::file_processor::FileChunk>* reactor) = 0;
      // Conversao de formato de imagem
      virtual void ConvertImageFormat(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::file_processor::FileChunk,::file_processor::FileChunk>* reactor) = 0;
      // Redimensionamento de imagem 
      virtual void ResizeImage(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::file_processor::FileChunk,::file_processor::FileChunk>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::FileChunk>* ConvertToTXTRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::FileChunk>* AsyncConvertToTXTRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::FileChunk>* PrepareAsyncConvertToTXTRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::FileChunk>* ConvertImageFormatRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::FileChunk>* AsyncConvertImageFormatRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::FileChunk>* PrepareAsyncConvertImageFormatRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::FileChunk>* ResizeImageRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::FileChunk>* AsyncResizeImageRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::FileChunk>* PrepareAsyncResizeImageRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>> ConvertToTXT(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>>(ConvertToTXTRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>> AsyncConvertToTXT(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>>(AsyncConvertToTXTRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>> PrepareAsyncConvertToTXT(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>>(PrepareAsyncConvertToTXTRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>> ConvertImageFormat(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>>(ConvertImageFormatRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>> AsyncConvertImageFormat(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>>(AsyncConvertImageFormatRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>> PrepareAsyncConvertImageFormat(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>>(PrepareAsyncConvertImageFormatRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>> ResizeImage(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>>(ResizeImageRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>> AsyncResizeImage(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>>(AsyncResizeImageRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>> PrepareAsyncResizeImage(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>>(PrepareAsyncResizeImageRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ConvertToTXT(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::file_processor::FileChunk,::file_processor::FileChunk>* reactor) override;
      void ConvertImageFormat(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::file_processor::FileChunk,::file_processor::FileChunk>* reactor) override;
      void ResizeImage(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::file_processor::FileChunk,::file_processor::FileChunk>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>* ConvertToTXTRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>* AsyncConvertToTXTRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>* PrepareAsyncConvertToTXTRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>* ConvertImageFormatRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>* AsyncConvertImageFormatRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>* PrepareAsyncConvertImageFormatRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>* ResizeImageRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>* AsyncResizeImageRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>* PrepareAsyncResizeImageRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ConvertToTXT_;
    const ::grpc::internal::RpcMethod rpcmethod_ConvertImageFormat_;
    const ::grpc::internal::RpcMethod rpcmethod_ResizeImage_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Conversao de PDF para TXT 
    virtual ::grpc::Status ConvertToTXT(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>* stream);
    // Conversao de formato de imagem
    virtual ::grpc::Status ConvertImageFormat(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>* stream);
    // Redimensionamento de imagem 
    virtual ::grpc::Status ResizeImage(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_ConvertToTXT : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ConvertToTXT() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ConvertToTXT() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ConvertToTXT(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestConvertToTXT(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ConvertImageFormat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ConvertImageFormat() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ConvertImageFormat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ConvertImageFormat(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestConvertImageFormat(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ResizeImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ResizeImage() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_ResizeImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ResizeImage(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestResizeImage(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(2, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ConvertToTXT<WithAsyncMethod_ConvertImageFormat<WithAsyncMethod_ResizeImage<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ConvertToTXT : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ConvertToTXT() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::file_processor::FileChunk, ::file_processor::FileChunk>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->ConvertToTXT(context); }));
    }
    ~WithCallbackMethod_ConvertToTXT() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ConvertToTXT(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::file_processor::FileChunk, ::file_processor::FileChunk>* ConvertToTXT(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ConvertImageFormat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ConvertImageFormat() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackBidiHandler< ::file_processor::FileChunk, ::file_processor::FileChunk>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->ConvertImageFormat(context); }));
    }
    ~WithCallbackMethod_ConvertImageFormat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ConvertImageFormat(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::file_processor::FileChunk, ::file_processor::FileChunk>* ConvertImageFormat(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ResizeImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ResizeImage() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackBidiHandler< ::file_processor::FileChunk, ::file_processor::FileChunk>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->ResizeImage(context); }));
    }
    ~WithCallbackMethod_ResizeImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ResizeImage(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::file_processor::FileChunk, ::file_processor::FileChunk>* ResizeImage(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_ConvertToTXT<WithCallbackMethod_ConvertImageFormat<WithCallbackMethod_ResizeImage<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ConvertToTXT : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ConvertToTXT() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ConvertToTXT() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ConvertToTXT(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ConvertImageFormat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ConvertImageFormat() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ConvertImageFormat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ConvertImageFormat(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ResizeImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ResizeImage() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_ResizeImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ResizeImage(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ConvertToTXT : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ConvertToTXT() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ConvertToTXT() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ConvertToTXT(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestConvertToTXT(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ConvertImageFormat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ConvertImageFormat() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ConvertImageFormat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ConvertImageFormat(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestConvertImageFormat(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ResizeImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ResizeImage() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_ResizeImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ResizeImage(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestResizeImage(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(2, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ConvertToTXT : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ConvertToTXT() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->ConvertToTXT(context); }));
    }
    ~WithRawCallbackMethod_ConvertToTXT() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ConvertToTXT(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* ConvertToTXT(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ConvertImageFormat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ConvertImageFormat() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->ConvertImageFormat(context); }));
    }
    ~WithRawCallbackMethod_ConvertImageFormat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ConvertImageFormat(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* ConvertImageFormat(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ResizeImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ResizeImage() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->ResizeImage(context); }));
    }
    ~WithRawCallbackMethod_ResizeImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ResizeImage(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::file_processor::FileChunk, ::file_processor::FileChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* ResizeImage(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace file_processor


#endif  // GRPC_file_5fprocessor_2eproto__INCLUDED
