# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_processor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'file_processor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66ile_processor.proto\x12\x0e\x66ile_processor\"\x1c\n\tFileChunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x32\xc2\x02\n\x14\x46ileProcessorService\x12G\n\x0b\x43ompressPDF\x12\x19.file_processor.FileChunk\x1a\x19.file_processor.FileChunk(\x01\x30\x01\x12H\n\x0c\x43onvertToTXT\x12\x19.file_processor.FileChunk\x1a\x19.file_processor.FileChunk(\x01\x30\x01\x12N\n\x12\x43onvertImageFormat\x12\x19.file_processor.FileChunk\x1a\x19.file_processor.FileChunk(\x01\x30\x01\x12G\n\x0bResizeImage\x12\x19.file_processor.FileChunk\x1a\x19.file_processor.FileChunk(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_processor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILECHUNK']._serialized_start=40
  _globals['_FILECHUNK']._serialized_end=68
  _globals['_FILEPROCESSORSERVICE']._serialized_start=71
  _globals['_FILEPROCESSORSERVICE']._serialized_end=393
# @@protoc_insertion_point(module_scope)
